batch_size: 1
val_batch_size: 1
sample_size: None # Set by the training loop, from dataset config.
sample_size_anchor: None # Set by the training loop, from dataset config.
num_wta_trials: 20
num_trials: 1
num_gmm_trials: 1

action_full: False