name: mu

# Model settings
type: point # (flow, point) Type of model
size: xS # (xs, s, ...) Architecture of DiT
in_channels: 3 # Number of input channels
learn_sigma: True # Learn sigma for diffusion
rotary: False # Use rotary embedding for diffusion
encoder_backbone: mlp # (mlp, pn2)
model_take: 1

x_encoder: mlp # Encoder current timestep x
y_encoder: mlp # (mlp, dgcnn) Encoder for y object (e.g. anchor pcd)
x0_encoder: mlp # (mlp, dgcnn) Encoder for x0 object (e.g. action pcd)

# diffusion settings
diff_train_steps: 100 # Number of diffusion steps during training
diff_inference_steps: 100 # Number of diffusion steps during inference
diff_noise_schedule: linear # (linear, cosine) Noise schedule for diffusion
diff_noise_scale: 1.0 # Scale of noise for diffusion
diff_type: gaussian
diff_translation_noise_scale: False # Scale of translation noise (in meter) for diffusion, or False for disable  
diff_rotation_noise_scale: False # scale of rotation noise (in degreee) for diffusion, or False for disable

# prediction setting
# centroid_frame: choose from ["anchor", "noisy_goal", "gmm"]
# anchor    : we are using anchor mean as the centroid of prediction (aka the original TAX3D setting)
# noisy_goal: we are using noisy_goal mean, or mean(goal_pc_action) + noise, as the centroid of prediction, 
#             to train our model to be robust with GMM prediction error
pred_ref_frame: anchor 
ref_error_scale: 1.0 # Scale factor for GMM prediction error

# TODO: GMM flags
