name: pn2_df

# Model settings
type: point # (flow, point) Type of model
size: xS # (xs, s, ...) Architecture of DiT
in_channels: 3 # Number of input channels
learn_sigma: True # Learn sigma for diffusion
center_noise: False # Center noise for diffusion
rotary: False # Use rotary embedding for diffusion
cross_atten: False # Use cross attention for diffusion
feature: off # (flow, point, off) Type of feature base
encoder_backbone: pn2 # (mlp, pn2)

# encoding before passing into PN2 (default to off)
x_pre_encoder: off # (mlp, off) Encoder current timestep x
y_pre_encoder: off # (mlp, dgcnn, off) Encoder for y object (e.g. anchor pcd)
x0_pre_encoder: off # (mlp, dgcnn, off) Encoder for x0 object (e.g. action pcd)

# diffusion settings
diff_train_steps: 100 # Number of diffusion steps during training
diff_inference_steps: 100 # Number of diffusion steps during inference
diff_noise_schedule: linear # (linear, cosine) Noise schedule for diffusion
diff_noise_scale: 1.0 # Scale of noise for diffusion
diff_type: gaussian