name: tax3dv2

#####################################################
# Model Architecture Parameters
#####################################################
type: point # (flow, point) Type of model
size: xS # (xs, s, ...) Architecture of DiT
in_channels: 3 # Number of input channels
learn_sigma: True # Learn sigma for diffusion
point_encoder: mlp # (mlp, pn2) Point cloud encoder architecture
feature: True # If True, encode additional features
joint_encode: True # If True, use joint encoding for point cloud feature
frame_type: fixed # (fixed, mu) Type of frame-prediction for the model

#####################################################
# Model-specific Dataset/Data-processing Parameters
#####################################################
# These override the dataset config.
pred_frame: anchor_center # [anchor_center, noisy_goal] frame for goal prediction
noisy_goal_scale: 0.0 # scale for simulated noisy goal error
action_context_frame: action_center # [action_center] frame for action context

#####################################################
# Dataset-specific Model Parameters
#####################################################
# These are shared and overriden by the dataset config.
pcd_scale: 1 # Scale range for the point clouds

#####################################################
# Model Diffusion Parameters
#####################################################
diff_train_steps: 100 # Number of diffusion steps during training
diff_inference_steps: 100 # Number of diffusion steps during inference
diff_noise_schedule: linear # (linear, cosine) Noise schedule for diffusion
diff_noise_scale: 1.0 # Scale of noise for diffusion
diff_type: gaussian
diff_translation_noise_scale: False # Scale of translation noise (in meter) for diffusion, or False for disable  
diff_rotation_noise_scale: False # scale of rotation noise (in degreee) for diffusion, or False for disable
time_based_weighting: even # (False, 'even', 'linear', 'sigmoid')