name: dedo

#####################################################
# Dataset Parameters
#####################################################
data_dir: "~/data/"
material: deform

train_size: null # (int, null) Length of the train dataset
val_size: null # (int, null) Length of the validation dataset

sample_size_action: 512
sample_size_anchor: 512
downsample_type: fps

#####################################################
# Model Dataset/Data-processing Parameters
#####################################################
# These are shared and overridden by the model config.
# noisy_goal: null # if True, use noisy action goal centroid
# center_type: null # [action_center, anchor_center, scene_center, none], centers the point clouds
# action_context_center_type: null # [center, random, none], centers the action context point clouds
pred_frame: null # frame for goal prediction
noisy_goal_scale: null # noise scale for simulated GMM error
action_context_frame: null # frame for action context

#####################################################
# Dataset-specific Model Parameters
#####################################################
# These override the model config.
pcd_scale: 12.0 # Scale range for the point clouds

#####################################################
# Environment-specific Parameters
#####################################################
task: proccloth
robot: True
cloth_geometry: multi
cloth_pose: random
anchor_geometry: single
anchor_pose: random
num_anchors: 2
hole: single

# Dataset pre-processing options
# center_type: anchor_center # [action_center, anchor_center, anchor_random, scene_center, none], centers the point clouds w.r.t. the action, anchor, or no centering
# action_context_center_type: center # [center, random, none], centers the action context point clouds
# action_transform_type: identity # Transformation type to apply to demonstrations
# anchor_transform_type: random_flat_upright # Transformation type to apply to demonstrations

#####################################################
# Data Processing/Augmentation Parameters
#####################################################
pcd_scale_factor: 1.0 # Scale factor for the point clouds
scene_transform_type: random_flat_upright # Transformation type to apply to the scene
translation_variance: 0.0 # Translation variance of the demo transformation
rotation_variance: 180 # Rotation variance of the demo transformation