name: insertion

#####################################################
# Dataset Parameters
#####################################################
data_dir: /data/lyuxing/tax3d/insertion/demonstrations/
material: rigid

###################################################
# Insertion Specifics
###################################################
connector_type: 04-21-dsub-1 # ['04-21-dsub-1', '04-21-wp-2']
data_type: learn_data

###################################################
# General Dataset Parameters
###################################################
num_demos: # Number of demonstrations to load
train_dataset_size: 100 # None: Use the length of loaded dataset
val_dataset_size: 8 # None: Use the length of loaded dataset
val_use_defaults: False # Use default values for some parameters on the validation set
preprocess: False

sample_size_action: 512
sample_size_anchor: 512
downsample_type: fps # [fps, random], downsampling method

#####################################################
# Model Dataset/Data-processing Parameters
#####################################################
# These are shared and overridden by the model config.
# noisy_goal: null # if True, use noisy action goal centroid
# center_type: null # [action_center, anchor_center, scene_center, none], centers the point clouds
# action_context_center_type: null # [center, random, none], centers the action context point clouds
pred_frame: null # frame for goal prediction
noisy_goal_scale: null # noise scale for simulated GMM error
action_context_frame: null # frame for action context

#####################################################
# Dataset-specific Model Parameters
#####################################################
# These override the model config.
pcd_scale: 1.0 # Scale range for the point clouds

#####################################################
# Data Processing/Augmentation Parameters
#####################################################
pcd_scale_factor: 50.0 
#action_transform_type: insertion_specific # Transformation type to apply to the action
#action_translation_variance: 0.1 # Translation variance of the action transformation
#action_rotation_variance: 0.52 # Rotation variance of the action transformation in radians
#anchor_transform_type: identity # Transformation type to apply to the anchor
#anchor_translation_variance: 0.1 # Translation variance of the anchor transformation
#anchor_rotation_variance: 0.52 # Rotation variance of the anchor transformation in radians
scene_transform_type: axis_angle # Transformation type to apply to the scene
translation_variance: 0.1 # Translation variance of the demo transformation
rotation_variance: 0.52 # Rotation variance of the demo transformation


###################################################
# Data Augmentation Parameters
###################################################
action_plane_occlusion: 0.0 # Probability of applying plane occlusion (0.8)
action_plane_standoff: 0.04 # Standoff distance of the occluding plane from selected plane origin
action_ball_occlusion: 0.8 # Probability of applying ball occlusion (0)
action_ball_radius: 0.5 # Radius of the occluding ball

anchor_plane_occlusion: 0 # Probability of applying plane occlusion (0)
anchor_plane_standoff: 0.04 # Standoff distance of the occluding plane from selected plane origin
anchor_ball_occlusion: 0.0 # Probability of applying ball occlusion (0.8)
anchor_ball_radius: 0.1 # Radius of the occluding ball