name: rpdiff_fit

#####################################################
# Dataset Parameters
#####################################################
data_dir: /data/lyuxing/tax3d/rpdiff/data/task_demos/
material: rigid

###################################################
# RPDiff Specifics
###################################################
rpdiff_task_name: mug_rack_easy_single
rpdiff_task_type: task_name_mug_on_rack
rpdiff_descriptions_path: /data/lyuxing/tax3d/rpdiff/descriptions/

###################################################
# General Dataset Parameters
###################################################
num_demos: 3 # Number of demonstrations to load
train_dataset_size: 200 # None: Use the length of loaded dataset
val_dataset_size: 1 # None: Use the length of loaded dataset
test_dataset_size: 1  # None: Use the length of loaded dataset
val_use_defaults: False # Use default values for some parameters on the validation set

sample_size_action: 512
sample_size_anchor: 512
downsample_type: fps # [fps, random], downsampling method

#####################################################
# Model Dataset/Data-processing Parameters
#####################################################
# These are shared and overridden by the model config.
# noisy_goal: null # if True, use noisy action goal centroid
# center_type: null # [action_center, anchor_center, scene_center, none], centers the point clouds
# action_context_center_type: null # [center, random, none], centers the action context point clouds
pred_frame: null # frame for goal prediction
noisy_goal_scale: null # noise scale for simulated GMM error
action_context_frame: null # frame for action context

#####################################################
# Dataset-specific Model Parameters
#####################################################
# These override the model config.
pcd_scale: null # Scale range for the point clouds

#####################################################
# Data Processing/Augmentation Parameters
#####################################################
pcd_scale_factor: 15.0 # Scale factor for the point clouds
scene_transform_type: random_flat_upright # Transformation type to apply to the scene
translation_variance: 0.0 # Translation variance of the demo transformation
rotation_variance: 180 # Rotation variance of the demo transformation

###################################################
# Data Augmentation Parameters
###################################################
action_plane_occlusion: 0.8 # Probability of applying plane occlusion (0.8)
action_plane_standoff: 0.04 # Standoff distance of the occluding plane from selected plane origin
action_ball_occlusion: 0 # Probability of applying ball occlusion (0)
action_ball_radius: 0.1 # Radius of the occluding ball

anchor_plane_occlusion: 0 # Probability of applying plane occlusion (0)
anchor_plane_standoff: 0.04 # Standoff distance of the occluding plane from selected plane origin
anchor_ball_occlusion: 0.8 # Probability of applying ball occlusion (0.8)
anchor_ball_radius: 0.1 # Radius of the occluding ball