name: rpdiff
data_dir: /data/lyuxing/tax3d/rpdiff/data/task_demos/
type: flow

material: rigid
scene: True
world_frame: True
noisy_goal: False

###################################################
# RPDiff Specifics
###################################################
rpdiff_task_name: mug_rack_easy_single
rpdiff_task_type: task_name_mug_on_rack
rpdiff_descriptions_path: /data/lyuxing/tax3d/rpdiff/descriptions/

###################################################
# General Dataset Parameters
# Full Config
num_demos: 3200 # Number of demonstrations to load
train_dataset_size: # None: Use the length of loaded dataset
val_dataset_size: 400 # None: Use the length of loaded dataset
test_dataset_size: 400  # None: Use the length of loaded dataset
val_use_defaults: False # Use default values for some parameters on the validation set
# Subset Config
#num_demos: 800 # Number of demonstrations to load
#train_dataset_size: # None: Use the length of loaded dataset
#val_dataset_size: 100 # None: Use the length of loaded dataset
#test_dataset_size: 100  # None: Use the length of loaded dataset
#val_use_defaults: True # Use default values for some parameters on the validation set

###################################################
# Point Cloud Transformation Parameters
###################################################
center_type: anchor_center # [action_center, anchor_center, anchor_random, none], centers the point clouds w.r.t. the action, anchor, or no centering
action_context_center_type: center # [center, random, none], centers the action context point clouds
sample_size_action: 512 # Number of points to downsample to
sample_size_anchor: 512 # Number of points to downsample to for the anchor
downsample_type: fps # [fps, random], downsampling method
pcd_scale_factor: 1 # Scale factor for the point clouds
ref_error_scale: 1 # Scale factor for GMM prediction error

action_transform_type: quat_uniform # Transformation type to apply to demonstrations
action_translation_variance: 0.0 # Translation variance of the demo transformation
action_rotation_variance: 180 # Rotation variance of the demo transformation

anchor_transform_type: random_flat_upright # Transformation type to apply to demonstrations
anchor_translation_variance: 0.5 # Translation variance of the demo transformation
anchor_rotation_variance: 180 # Rotation variance of the demo transformation

###################################################
# Distractor parameters
###################################################
distractor_anchor_pcds: 0 # Number of distractor anchor pcds to generate
distractor_transform_type: random_flat_upright # Transformation type to apply when generating distractor pcds
distractor_translation_variance: 0.5 # Translation variance of the distractor transformation
distractor_rotation_variance: 180 # Rotation variance of the distractor transformation

###################################################
# Data Augmentation Parameters
###################################################
action_plane_occlusion: 0.8 # Probability of applying plane occlusion (0.8)
action_plane_standoff: 0.04 # Standoff distance of the occluding plane from selected plane origin
action_ball_occlusion: 0 # Probability of applying ball occlusion (0)
action_ball_radius: 0.1 # Radius of the occluding ball

anchor_plane_occlusion: 0 # Probability of applying plane occlusion (0)
anchor_plane_standoff: 0.04 # Standoff distance of the occluding plane from selected plane origin
anchor_ball_occlusion: 0.8 # Probability of applying ball occlusion (0.8)
anchor_ball_radius: 0.1 # Radius of the occluding ball