mode: eval

# This is somewhat arbitrary.
job_type: ${mode}_${dataset.name}

defaults:
  # Each of these have their own configuration parameters.
  - dataset: rpdiff
  - model: df_cross

  # A set of inference settings for the model. Note that these may be different
  # from / or a subset of the training settings. This is that we don't have to
  # provide, like, a learning rater or something to eval.
  - inference: ${dataset}_${model}

  # Simple shared imports.
  - _logging

  # Override.
  - _self_

seed: 42
# task_type: null # Set during eval loop based on dataset.
gmm: null # (None, num_epochs) If not None, use GMM for eval.
gmm_pcd_scale: s3
gmm_log_dir: "/home/lyuxing/Desktop/tax3d_upgrade/scripts/logs/gmm_outputs"

exp_name: null

# This is the checkpoint that we're evaluating. You can change this to whatever you need,
# like if you want multiple checkpoints simultaneously, etc.
checkpoint:
  # If we want to load a model for a specific run, we can change that here.
  run_id: ???
  alias: v0 # (v0, monitor); v0 is the last checkpoint, monitor is best monitor-specific checkpoint
  monitor_name: val_rmse_0
  #reference: ${wandb.entity}/${wandb.project}/model-${checkpoint.run_id}:${checkpoint.alias}
  reference: /home/lyuxing/Desktop/tax3d_realworld/last.ckpt

resources:
  num_workers: 4
  gpus:
    - 0

wandb:
  # The group ***should*** be the same as the training group (so it can be bundled)
  # nicely in the UI. But you might have a one-off eval or something.
  group: ???
